### ISSUE TITLE
Code run time issue

### ISSUE THREAD

**Issue by srkadiyala** [dineshonjava/SpringBootSpringDataSolrCrudExample#1]
Hi Dinesh,

You need to add the following minor changes to code:

SolrConfig.java: (Missed to define externalized props file)
@EnableSolrRepositories(basePackages = "com.deloittelabs.app.repository", namedQueriesLocation = "classpath:solr-named-queries.properties")

Add solr-names-quareis.properties file to resources folder. Add the following line in that props file.
Order.findByNamedQuery=id:*?0* OR name:*?0*

After above modifications, code runs.

**Comment by srkadiyala** [comment]
Forgot to mention, thanks for sharing code in github. May be it is good idea to write data injection statement as part of the code.

**Comment by dineshonjava** [comment]
Thanks for your feedback. I have added missing configuration file.
