### ISSUE TITLE
 Error in @Value SolrConfig

### ISSUE THREAD

**Issue by juliocesarsantos1020** [dineshonjava/SpringBootSpringDataSolrCrudExample#2]
The @value of solrURL is an error, the correct one is @Value ("$ {spring.data.solr.host}")

**Comment by dineshonjava** [comment]
Okay...

**Comment by Sarahhtammam** [comment]
Why did you mark it as closed, it's still not pushed and It took me an hour to figure it out 😃 !!

**Comment by dineshonjava** [comment]
Forgot to commit. :)
